# Generated by Django 5.0.6 on 2026-05-17 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openai_api_key', models.CharField(blank=True, help_text='Company-specific OpenAI key (overrides global)', max_length=200)),
                ('openai_model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100)),
                ('openai_embedding_model', models.CharField(blank=True, default='text-embedding-3-small', max_length=100)),
                ('telegram_api_id', models.CharField(blank=True, help_text='From my.telegram.org/apps', max_length=20)),
                ('telegram_api_hash', models.CharField(blank=True, max_length=64)),
                ('telegram_bot_token', models.CharField(blank=True, help_text='From @BotFather', max_length=200)),
                ('telegram_bot_username', models.CharField(blank=True, max_length=100)),
                ('telegram_bot_webhook_secret', models.CharField(blank=True, max_length=64)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_reply_delay_min', models.PositiveIntegerField(default=2, help_text='Seconds')),
                ('ai_reply_delay_max', models.PositiveIntegerField(default=8, help_text='Seconds')),
                ('daily_message_limit', models.PositiveIntegerField(default=200)),
                ('ai_language', models.CharField(default='auto', help_text="'auto' detects language, or set e.g. 'uz', 'ru', 'en'", max_length=10)),
                ('notify_email', models.EmailField(blank=True, help_text='Send alerts to this email', max_length=254)),
                ('notify_on_new_lead', models.BooleanField(default=True)),
                ('notify_on_qualified_lead', models.BooleanField(default=True)),
                ('company_description', models.TextField(blank=True, help_text='Used in AI system prompts')),
                ('products_services', models.TextField(blank=True, help_text='List of products/services for AI context')),
                ('support_contact', models.CharField(blank=True, max_length=200)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_settings', to='accounts.organization')),
            ],
            options={
                'db_table': 'organization_settings',
            },
        ),
    ]
