# Generated by Django 5.0.6 on 2026-05-17 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('buying_intent_score', models.FloatField(default=0.0)),
                ('extracted_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_interests', models.JSONField(default=list)),
                ('last_agent', models.CharField(blank=True, max_length=20)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='crm.lead')),
            ],
            options={
                'db_table': 'conversation_memories',
            },
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.organization')),
                ('target_leads', models.ManyToManyField(blank=True, related_name='campaigns', to='crm.lead')),
            ],
            options={
                'db_table': 'outreach_campaigns',
            },
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_sent', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
                ('reply_text', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_agents.outreachcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='crm.lead')),
            ],
            options={
                'db_table': 'outreach_logs',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('agent_type', models.CharField(choices=[('reception', 'Reception Agent'), ('qualification', 'Qualification Agent'), ('sales', 'Sales Conversation Agent'), ('followup', 'Follow-Up Agent'), ('proposal', 'Proposal Generator'), ('sentiment', 'Sentiment Analysis')], max_length=20)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='accounts.organization')),
            ],
            options={
                'db_table': 'prompts',
                'ordering': ['agent_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(max_length=20)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(max_length=50)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'agent_type', 'created_at'], name='ai_logs_organiz_f63ed3_idx')],
            },
        ),
    ]
