# Generated by Django 5.0.6 on 2026-05-17 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('new_leads', models.PositiveIntegerField(default=0)),
                ('qualified_leads', models.PositiveIntegerField(default=0)),
                ('won_deals', models.PositiveIntegerField(default=0)),
                ('lost_deals', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('ai_responses', models.PositiveIntegerField(default=0)),
                ('followups_sent', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='accounts.organization')),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
