# Generated by Django 5.0.6 on 2026-05-17 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('session_string', models.TextField(blank=True, help_text='Telethon StringSession')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Login'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('is_ai_enabled', models.BooleanField(default=True, help_text='Enable AI auto-reply')),
                ('ai_delay_min', models.PositiveIntegerField(default=2, help_text='Min delay seconds before reply')),
                ('ai_delay_max', models.PositiveIntegerField(default=8, help_text='Max delay seconds before reply')),
                ('daily_message_limit', models.PositiveIntegerField(default=50)),
                ('messages_sent_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to='accounts.organization')),
            ],
            options={
                'db_table': 'telegram_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_code_hash', models.CharField(blank=True, max_length=100)),
                ('awaiting_code', models.BooleanField(default=False)),
                ('awaiting_2fa', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_state', to='telegram_bot.telegramaccount')),
            ],
            options={
                'db_table': 'telegram_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_message_id', models.BigIntegerField()),
                ('sender_id', models.BigIntegerField()),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('chat_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegramaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='accounts.organization')),
            ],
            options={
                'db_table': 'telegram_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender_id', 'account'], name='telegram_me_sender__9925f4_idx'), models.Index(fields=['organization', 'direction'], name='telegram_me_organiz_71b3ad_idx')],
            },
        ),
    ]
