# Generated by Django 5.0.6 on 2026-05-17 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizationsettings'),
        ('crm', '0001_initial'),
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('userbot', 'Userbot (MTProto)'), ('bot', 'Bot API')], default='bot', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('message_text', models.TextField(help_text="Yuborilajak xabar matni. {name} o'zgaruvchisi qo'llaniladi.")),
                ('parse_mode', models.CharField(choices=[('HTML', 'HTML'), ('Markdown', 'Markdown'), ('plain', 'Plain Text')], default='HTML', max_length=10)),
                ('target_all_leads', models.BooleanField(default=False, help_text='Barcha leadlarga yuborish')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (no Telegram ID)')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('personalized_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'broadcast_recipients',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Bot nomi (eslatma uchun)', max_length=150)),
                ('bot_token', models.CharField(help_text='@BotFather dan olingan token', max_length=200, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=100)),
                ('bot_id', models.BigIntegerField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook xavfsizlik kaliti', max_length=64)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('error', 'Error')], default='inactive', max_length=20)),
                ('is_ai_enabled', models.BooleanField(default=True)),
                ('ai_delay_min', models.PositiveIntegerField(default=1)),
                ('ai_delay_max', models.PositiveIntegerField(default=5)),
                ('daily_message_limit', models.PositiveIntegerField(default=500)),
                ('messages_sent_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'telegram_bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='telegrammessage',
            name='telegram_me_sender__9925f4_idx',
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='source',
            field=models.CharField(choices=[('userbot', 'Userbot'), ('bot', 'Bot API')], default='userbot', max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='ai_delay_max',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='ai_delay_min',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='is_ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegramaccount'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='telegram_message_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='target_leads',
            field=models.ManyToManyField(blank=True, help_text='Aniq leadlar tanlanganda', related_name='broadcasts', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='userbot_account',
            field=models.ForeignKey(blank=True, help_text='Userbot tanlanganda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='telegram_bot.telegramaccount'),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='telegram_bot.broadcast'),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Bot API tanlanganda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='telegram_bot.telegrambot'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegrambot'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['sender_id', 'organization'], name='telegram_me_sender__3cc7cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together={('broadcast', 'lead')},
        ),
    ]
